services:
  # Vector database for RAG
  # UI interface at http://localhost:6333/dashboard
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    restart: unless-stopped
    networks:
      - exist
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

networks:
  exist:
    external: true
