services:
  reverse-proxy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    networks:
      - exist
    env_file:
      - ../.env
    ports:
      - "80:80" # The HTTP port
      - "443:443" # The HTTP port
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  exist:
    external: true
