services:
  reverse-proxy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    networks:
      exist:
        ipv4_address: 172.18.0.5 # Verify by running `docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' caddy`
    env_file:
      - ../.env
    ports:
      - "80:80" # The HTTP port
      - "443:443" # The HTTP port
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ../Cloudflare/cloudflare.pem:/etc/caddy/certs/cloudflare.crt:ro
      - ../Cloudflare/cloudflare-key.pem:/etc/caddy/certs/cloudflare.key:ro
    environment:
      - CADDY_INGRESS_NETWORKS=exist

volumes:
  caddy_data:
  caddy_config:

networks:
  exist:
    external: true
