services:
  appsmith:
    container_name: appsmith
    image: index.docker.io/appsmith/appsmith-ce
    restart: unless-stopped
    networks:
      - exist
    ports:
      # - "80:80"
      - "4443:80"
    volumes:
      - appsmith_data:/appsmith-stacks

  # nuke:
  #   image: node:20-alpine
  #   entrypoint: >
  #     sh -c '
  #       sleep 500
  #     '
  #   restart: "no"
  #   volumes:
  #     - appsmith_data:/appsmith-stacks

volumes:
  appsmith_data: # appsmith_data dataset will need to be created in TrueNAS
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${TRUENAS_SERVER_ADDRESS},nolock,soft,rw,nfsvers=4"
      device: ":${TRUENAS_CONTAINER_PATH}/appsmith_data"

networks:
  exist:
    external: true
