services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    restart: unless-stopped
    networks:
      - exist
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "1883:1883"   # MQTT protocol
      - "8883:8883"   # Secure MQTT protocol
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./ssl:/etc/rabbitmq/ssl:ro
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  rabbitmq-webhook-bridge:
    container_name: rabbitmq-webhook-bridge
    image: rabbitmq-webhook-bridge
    build: ./webhook-bridge
    env_file:
      - ./webhook-bridge/.env
    networks:
      - exist
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    init: true

volumes:
  rabbitmq_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${TRUENAS_SERVER_ADDRESS},nolock,soft,rw,nfsvers=4"
      device: ":${TRUENAS_CONTAINER_PATH}/rabbitmq_data"

networks:
  exist:
    external: true
