services:
  # Object storage for Nextcloud
  # UI interface at http://localhost:9001
  minio:
    container_name: minio
    image: minio/minio:latest
    restart: unless-stopped
    networks:
      - exist
    env_file:
      - ../.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data # Path to the mounted NFS share on the Proxmox host
    command: server /data --console-address :9001

volumes:
  minio_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${TRUENAS_SERVER_ADDRESS},nolock,soft,rw,nfsvers=4"
      device: ":${TRUENAS_PATH}"

networks:
  exist:
    external: true
