services:
  # Object storage for Nextcloud
  # UI interface at http://localhost:9001
  minio:
    container_name: minio
    image: minio/minio:latest
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /mnt/minio_data:/data # Path to the mounted NFS share on the Proxmox host
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address :9001
