services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      # - 40800:8000
      - 49443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./portainer_password.txt:/shared/portainer_password.txt:ro
    networks:
      - exist
    restart: unless-stopped
    command: >
      -H unix:///var/run/docker.sock
      --admin-password-file /shared/portainer_password.txt

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${TRUENAS_SERVER_ADDRESS},nolock,soft,rw,nfsvers=4"
      device: ":${TRUENAS_CONTAINER_PATH}/portainer_data"

networks:
  exist:
    external: true
