services: 
  nocodb_postgres: 
    container_name: nocodb_postgres
    image: postgres:16.6
    restart: unless-stopped
    env_file:
      - ../.env
    environment: 
      POSTGRES_DB: nocodb_postgres
      POSTGRES_PASSWORD: ${NOCODB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${NOCODB_POSTGRES_USER}
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    volumes: 
      - "./ncpg_data:/var/lib/postgresql/data"

  # UI interface at http://localhost:11580/
  nocodb: 
    container_name: nocodb
    image: "nocodb/nocodb:latest"
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on: 
      nocodb_postgres: 
        condition: service_healthy
    environment: 
      NC_DB: "pg://nocodb_postgres:5432?u=${NOCODB_POSTGRES_USER}&p=${NOCODB_POSTGRES_PASSWORD}&d=nocodb_postgres"
    ports: 
      - "11580:8080"
    volumes: 
      - "./nc_data:/usr/app/data"
