services:
  nsqlookupd:
    container_name: nsqlookupd
    image: nsqio/nsq
    restart: unless-stopped
    env_file:
      - ../.env
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"

  nsqd:
    container_name: nsqd
    image: nsqio/nsq
    restart: unless-stopped
    env_file:
      - ../.env
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"

  nsqadmin:
    container_name: nsqadmin
    image: nsqio/nsq
    restart: unless-stopped
    env_file:
      - ../.env
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171"
