services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - exist
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

networks:
  exist:
    external: true
