services:
  vikunja:
    container_name: vikunja
    image: vikunja/vikunja
    restart: unless-stopped
    networks:
      - exist
    ports:
      - 3456:3456
    environment:
      VIKUNJA_SERVICE_PUBLICURL: ${VIKUNJA_SERVICE_PUBLICURL}
      VIKUNJA_DATABASE_HOST: ${VIKUNJA_DATABASE_HOST}
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_DATABASE_PASSWORD}
      VIKUNJA_DATABASE_TYPE: ${VIKUNJA_DATABASE_TYPE}
      VIKUNJA_DATABASE_USER: ${VIKUNJA_DATABASE_USER}
      VIKUNJA_DATABASE_DATABASE: ${VIKUNJA_DATABASE_DATABASE}
      VIKUNJA_SERVICE_ENABLEREGISTRATION: ${VIKUNJA_SERVICE_ENABLEREGISTRATION}
    volumes:
      - vikunja_data:/app/vikunja/files
    depends_on:
      vikunja_db:
        condition: service_healthy

  vikunja_db:
    container_name: vikunja_db
    image: postgres:17
    restart: unless-stopped
    networks:
      - exist
    environment:
      POSTGRES_PASSWORD: ${VIKUNJA_DATABASE_PASSWORD}
      POSTGRES_USER: ${VIKUNJA_DATABASE_USER}
    volumes:
      - vikunja_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s
      start_period: 30s

  vikunja_user_init:
    image: vikunja/vikunja
    depends_on:
      vikunja_db:
        condition: service_healthy
    networks:
      - exist
    environment:
      VIKUNJA_DATABASE_HOST: ${VIKUNJA_DATABASE_HOST}
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_DATABASE_PASSWORD}
      VIKUNJA_DATABASE_TYPE: ${VIKUNJA_DATABASE_TYPE}
      VIKUNJA_DATABASE_USER: ${VIKUNJA_DATABASE_USER}
      VIKUNJA_DATABASE_DATABASE: ${VIKUNJA_DATABASE_DATABASE}
    entrypoint: >
      /app/vikunja/vikunja user create
      --username ${VIKUNJA_DEFAULT_USERNAME}
      --password ${VIKUNJA_DEFAULT_PASSWORD}
      --email ${VIKUNJA_DEFAULT_EMAIL}
    restart: "no"

volumes:
  vikunja_data: # vikunja_data dataset will need to be created in TrueNAS
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${TRUENAS_SERVER_ADDRESS},nolock,soft,rw,nfsvers=4"
      device: ":${TRUENAS_CONTAINER_PATH}/vikunja_data"
  vikunja_db_data: # vikunja_db_data dataset will need to be created in TrueNAS
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${TRUENAS_SERVER_ADDRESS},nolock,soft,rw,nfsvers=4"
      device: ":${TRUENAS_CONTAINER_PATH}/vikunja_db_data"

networks:
  exist:
    external: true
